# Generated by Django 3.1.4 on 2022-03-15 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playmate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('description', models.TextField(default='One night stand, gangbag, both?')),
                ('slug', models.SlugField()),
                ('play_count', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playmates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
