# Generated by Django 3.1.4 on 2022-03-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playmates_app', '0003_alter_playmate_description_alter_playmate_id_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playmate',
            name='slug',
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='playmate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='playmates_app.playmate'),
        ),
        migrations.AlterField(
            model_name='playmate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
